# What I want to do here, is practice with real data from the 2022 Stack Overflow survey, to get some insights. 

1. First of all, I just want to get just an overview about the data I wanna work


In [2]:
import pandas as pd
import numpy as np
original_df = pd.read_csv('/Users/daniboy/Desktop/Youtube_Courses/Pandas_Corey_Schafer/stack-overflow-developer-survey-2022/survey_results_public.csv')
df_schema = pd.read_csv('/Users/daniboy/Desktop/Youtube_Courses/Pandas_Corey_Schafer/stack-overflow-developer-survey-2022/survey_results_schema.csv')
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [26]:
original_df.head(10)

ResponseId                                         MainBranch   
0           1                                      None of these  \
1           2                     I am a developer by profession   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   
5           6  I am not primarily a developer, but I write co...   
6           7                        I code primarily as a hobby   
7           8                     I am a developer by profession   
8           9                     I am a developer by profession   
9          10                     I am a developer by profession   

                                          Employment   
0                                                NaN  \
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4                                Employed, full-time   
5                                 Student, full-time   
6                                 Student, part-time   
7                 Not employed, but looking for work   
8                                Employed, full-time   
9  Independent contractor, freelancer, or self-em...   

                             RemoteWork   
0                                   NaN  \
1                          Fully remote   
2  Hybrid (some remote, some in-person)   
3                          Fully remote   
4  Hybrid (some remote, some in-person)   
5                                   NaN   
6                                   NaN   
7                                   NaN   
8  Hybrid (some remote, some in-person)   
9                          Fully remote   

                                    CodingActivities   
0                                                NaN  \
1           Hobby;Contribute to open-source projects   
2                                              Hobby   
3                       I don’t code outside of work   
4                                              Hobby   
5                                                NaN   
6                                                NaN   
7                                                NaN   
8                       I don’t code outside of work   
9  Hobby;Contribute to open-source projects;Boots...   

                                             EdLevel   
0                                                NaN  \
1                                                NaN   
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
5    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
6  Secondary school (e.g. American high school, G...   
7  Some college/university study without earning ...   
8    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
9  Some college/university study without earning ...   

                                           LearnCode   
0                                                NaN  \
1                                                NaN   
2  Books / Physical media;Friend or family member...   
3  Books / Physical media;School (i.e., Universit...   
4  Other online resources (e.g., videos, blogs, f...   
5  Books / Physical media;School (i.e., Universit...   
6  Other online resources (e.g., videos, blogs, f...   
7                    Online Courses or Certification   
8                On the job training;Coding Bootcamp   
9  Books / Physical media;Other online resources ...   

                                     LearnCodeOnline LearnCodeCoursesCert   
0                                                NaN                  NaN  \
1                                                NaN                  NaN   
2  Technical documentation;Blogs;Programming Game...                  NaN   
3   

In [25]:
df_schema.loc['Onboarding']['question']

'The time it takes to onboard new hires at my company is:'

In [24]:
df_schema.loc['ICorPM']['question']

'Are you an independent contributor or people manager?'

In [20]:
original_df['TBranch'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [23]:
df_schema.head()
df_schema.set_index('qname', inplace=True)
df_schema.loc['TBranch']['question']

'<span style="font-size:16px;">Would you like to participate in the Professional Developer Series?</span>'

In [19]:
original_df['Ethnicity'].value_counts()

Ethnicity
European                                             14612
White                                                13633
White;European                                        8694
Indian                                                5240
Asian                                                 3346
                                                     ...  
Indian;European;African;Multiracial                      1
Asian;East Asian;Southeast Asian;Pacific Islander        1
Middle Eastern;Asian;Multiracial;Biracial                1
Or, in your own words:;European;Asian                    1
White;European;North African;Hispanic or Latino/a        1
Name: count, Length: 1055, dtype: int64

### <span style="color:magenta;font-family:cursive;">More European people than white people?</span>

In [17]:
original_df['MiscTechHaveWorkedWith'].unique()

array([nan, 'Pandas', '.NET', ...,
       'Apache Spark;Hadoop;Keras;NumPy;Pandas',
       '.NET;Apache Kafka;NumPy;Spring',
       'Apache Kafka;Flutter;Hadoop;Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Torch/PyTorch'],
      dtype=object)

In [15]:
original_df['PlatformHaveWorkedWith'].value_counts()

PlatformHaveWorkedWith
AWS                                                                                                                                     8719
Microsoft Azure                                                                                                                         4989
Google Cloud                                                                                                                            2306
AWS;Microsoft Azure                                                                                                                     2039
Heroku                                                                                                                                  2003
                                                                                                                                        ... 
AWS;Colocation;Firebase;Google Cloud;IBM Cloud or Watson;OpenStack;VMware                                                          

In [12]:
original_df['PlatformWantToWorkWith'].value_counts()

PlatformWantToWorkWith
AWS                                                                                                                                 7350
Microsoft Azure                                                                                                                     3568
AWS;Google Cloud                                                                                                                    2025
AWS;Microsoft Azure                                                                                                                 2000
Google Cloud                                                                                                                        1957
                                                                                                                                    ... 
Colocation;Managed Hosting;Oracle Cloud Infrastructure                                                                                 1
AWS;Colocation;Goo

In [14]:
original_df['PlatformWantToWorkWith'].isna().sum()

32853

In [16]:
original_df['PlatformWantToWorkWith'].shape

(73268,)

### <span style="color:magenta;font-family:cursive;">I think the best platform to learn how to use is AWS.</span>
Tons of people don't know how to use it

In [11]:
original_df['DatabaseHaveWorkedWith'].value_counts()

DatabaseHaveWorkedWith
MySQL                                                                3563
PostgreSQL                                                           3519
Microsoft SQL Server                                                 3238
SQLite                                                               2022
MongoDB                                                              1655
                                                                     ... 
Elasticsearch;IBM DB2;MongoDB;MySQL                                     1
Cloud Firestore;Microsoft SQL Server;MongoDB;MySQL;Neo4j                1
Cloud Firestore;MongoDB;Oracle;PostgreSQL;Redis;SQLite                  1
MariaDB;Microsoft SQL Server;MySQL;Neo4j;Oracle;PostgreSQL;SQLite       1
Microsoft SQL Server;Neo4j;Redis                                        1
Name: count, Length: 4223, dtype: int64

In [10]:
original_df['DatabaseWantToWorkWith'].value_counts()

DatabaseWantToWorkWith
PostgreSQL                                                                                           3994
Microsoft SQL Server                                                                                 2025
MongoDB                                                                                              1850
MySQL                                                                                                1806
SQLite                                                                                               1532
                                                                                                     ... 
Cloud Firestore;IBM DB2;MongoDB;PostgreSQL;Redis                                                        1
Couchbase;MongoDB;Oracle;PostgreSQL                                                                     1
Cassandra;DynamoDB;Elasticsearch;MariaDB;Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;Redis            1
Cassandra;DynamoDB;Elas

### <span style="color:magenta;font-family:cursive;">Why does the people want to work with PostgreSQL, and switch from MySQL?</span>

In [8]:
original_df['BuyNewTool'].unique()

array([nan, 'Other (please specify):',
       'Start a free trial;Visit developer communities like Stack Overflow',
       'Start a free trial',
       'Start a free trial;Ask developers I know/work with;Research companies that have advertised on sites I visit',
       'Start a free trial;Visit developer communities like Stack Overflow;Ask developers I know/work with',
       'Start a free trial;Ask developers I know/work with',
       'Visit developer communities like Stack Overflow',
       'Start a free trial;Research companies that have advertised on sites I visit',
       'Visit developer communities like Stack Overflow;Ask developers I know/work with',
       'Other (please specify):;Start a free trial;Research companies that have advertised on sites I visit',
       'Ask developers I know/work with',
       'Start a free trial;Visit developer communities like Stack Overflow;Read ratings or reviews on third party sites like G2Crowd',
       'Other (please specify):;Ask developers

In [9]:
original_df['PurchaseInfluence'].unique()

array([nan, 'I have some influence', 'I have little or no influence',
       'I have a great deal of influence'], dtype=object)

In [5]:
original_df['MainBranch'].unique()

array(['None of these', 'I am a developer by profession',
       'I am not primarily a developer, but I write code sometimes as part of my work',
       'I code primarily as a hobby', 'I am learning to code',
       'I used to be a developer by profession, but no longer am'],
      dtype=object)

In [6]:
original_df['DevType'].unique()

array([nan,
       'Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site reliability',
       'Developer, full-stack', ...,
       'Data scientist or machine learning specialist;Developer, front-end;Developer, full-stack;Developer, back-end;Developer, QA or test;Developer, mobile;Database administrator;Cloud infrastructure engineer;Data or business analyst;Designer;Blockchain',
       'Developer, front-end;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise applications;Developer, mobile;Educator;Developer, embedded applications or devices',
       'Developer, front-end;Engineer, data;Engineer, site reliability;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise applications;Developer, QA or test;Student;Developer, mobile;Academic researcher;DevOps specialist;Developer, embedded applications or devices;Developer, game or graphics;Cloud infrastructure engineer;Data or business analyst;Designer;Scie

In [4]:
df_schema.head()

qid       qname                                           question   
0   QID16          S0  <div><span style="font-size:19px;"><strong>Hel...  \
1   QID12    MetaInfo                                  Browser Meta Info   
2    QID1          S1  <span style="font-size:22px; font-family: aria...   
3    QID2  MainBranch  Which of the following options best describes ...   
4  QID296  Employment  Which of the following best describes your cur...   

  force_resp  type selector  
0      False    DB       TB  
1      False  Meta  Browser  
2      False    DB       TB  
3       True    MC     SAVR  
4      False    MC     MAVR

#### I just want to grab some specific columns from the original dataset. Instead of droping tons of columns, I prefer to create a new df to work with. So, let's clean the data 

In [28]:
interest_columns = ['ResponseId','MainBranch','Employment','RemoteWork','EdLevel','YearsCode','DevType','PurchaseInfluence','LanguageHaveWorkedWith','DatabaseHaveWorkedWith','PlatformHaveWorkedWith','OpSysProfessional use','OpSysPersonal use','Age','Gender','Ethnicity','WorkExp','ConvertedCompYearly']
len(interest_columns)

18